/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.iit.cs445.spring22;

import java.util.Random;

public class App extends Random {
	
	public App() {
		super();	
	}
	
	public App(long seed) {
		super(seed);
	}
	
	public int randomWithBounds (int lower, int upper) {
		int number;
		number = (int) (Math.random() * (upper - lower)) + lower;
		return number;
	}
	
	public static void main(String[] args) {
		App random = new App();
		System.out.println(random.randomWithBounds(1, 89));
	}
}