/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.iit.cs445.spring22;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
	
	@Test
	public void AppTestClass () {
		App random = new App();
		System.out.println(random.randomWithBounds(1, 89));
	}
}